name = "MonolithicFEMVLFS"
uuid = "02a35734-3e3a-4c9f-8994-84c0fbc3ad2f"
authors = ["Oriol Colomes <oriol.colomes@gmail.com>"]
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
TickTock = "9ff05d80-102d-5586-aa04-3a8bd1a90d20"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
WaveSpec = "908d4cf6-a6c0-449c-92e4-852c8f288332"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
CSV = "0.10.4"
DataFrames = "1.3.2"
DataFramesMeta = "0.10.0"
DrWatson = "2.9.1"
Gridap = "0.17.12"
LaTeXStrings = "1.3.0"
Parameters = "0.12.3"
Roots = "2.0.0"
WriteVTK = "1.14.2"
julia = "1.6"
